name = "adecore-docs"
compatibility_date = "2026-09-01"
routes = [{ pattern = "adecore.dev", custom_domain = true }]

[assets]
directory = "./docs/.vitepress/dist"
not_found_handling = "404-page"

[observability]
enabled = true
