import { ChatAttachmentUploadSchema, type ChatAttachmentUpload } from '@adecore/agent-contracts';

interface ImageInfo {
    mime: string;
    extension: string;
    width?: number;
    height?: number;
}

function imageInfo(bytes: Buffer): ImageInfo | null {
    if (
        bytes.length >= 33 &&
        bytes.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])) &&
        bytes.readUInt32BE(8) === 13 &&
        bytes.toString('ascii', 12, 16) === 'IHDR'
    ) {
        return { mime: 'image/png', extension: 'png', width: bytes.readUInt32BE(16), height: bytes.readUInt32BE(20) };
    }
    if (bytes.length >= 13 && /GIF8[79]a/.test(bytes.toString('ascii', 0, 6))) {
        return { mime: 'image/gif', extension: 'gif', width: bytes.readUInt16LE(6), height: bytes.readUInt16LE(8) };
    }
    if (
        bytes.length >= 20 &&
        bytes.toString('ascii', 0, 4) === 'RIFF' &&
        bytes.toString('ascii', 8, 12) === 'WEBP' &&
        bytes.readUInt32LE(4) + 8 === bytes.length
    ) {
        const kind = bytes.toString('ascii', 12, 16);
        if (kind === 'VP8X' && bytes.length >= 30) {
            return { mime: 'image/webp', extension: 'webp', width: bytes.readUIntLE(24, 3) + 1, height: bytes.readUIntLE(27, 3) + 1 };
        }
        if (kind === 'VP8 ' && bytes.length >= 30 && bytes.subarray(23, 26).equals(Buffer.from([157, 1, 42]))) {
            return { mime: 'image/webp', extension: 'webp', width: bytes.readUInt16LE(26) & 0x3fff, height: bytes.readUInt16LE(28) & 0x3fff };
        }
        if (kind === 'VP8L' && bytes.length >= 25 && bytes[20] === 0x2f) {
            const size = bytes.readUInt32LE(21);
            return { mime: 'image/webp', extension: 'webp', width: (size & 0x3fff) + 1, height: ((size >> 14) & 0x3fff) + 1 };
        }
        return null;
    }
    if (bytes.length >= 4 && bytes[0] === 255 && bytes[1] === 216 && bytes[2] === 255) {
        let offset = 2;
        while (offset + 4 <= bytes.length && bytes[offset] === 255) {
            const marker = bytes[offset + 1]!;
            if (marker === 218 || marker === 217) {
                break;
            }
            if (marker === 255) {
                offset++;
                continue;
            }
            const size = bytes.readUInt16BE(offset + 2);
            if (size < 2 || offset + 2 + size > bytes.length) {
                return null;
            }
            if ([192, 193, 194, 195, 197, 198, 199, 201, 202, 203, 205, 206, 207].includes(marker) && size >= 8) {
                return { mime: 'image/jpeg', extension: 'jpg', width: bytes.readUInt16BE(offset + 7), height: bytes.readUInt16BE(offset + 5) };
            }
            offset += size + 2;
        }
    }
    return null;
}

export function generatedImage(data: string, prompt?: string): { upload: ChatAttachmentUpload; width?: number; height?: number } {
    const parsed = ChatAttachmentUploadSchema.safeParse({ name: 'image', mime: 'application/octet-stream', data });
    if (!parsed.success) {
        throw new Error('The generated image is empty, invalid base64 or exceeds 10 MiB');
    }
    const bytes = Buffer.from(data, 'base64');
    // Buffer's decoder accepts malformed padding and trailing bits; the protocol requires canonical base64.
    if (bytes.toString('base64') !== data) {
        throw new Error('The generated image contains invalid base64');
    }
    const info = imageInfo(bytes);
    if (info === null || (info.width !== undefined && info.width === 0) || (info.height !== undefined && info.height === 0)) {
        throw new Error('The generated bytes are not a supported image');
    }
    const stem =
        (prompt ?? '')
            .normalize('NFKD')
            .replace(/[^a-zA-Z0-9]+/g, '-')
            .replace(/^-|-$/g, '')
            .slice(0, 80)
            .toLowerCase() || 'generated-image';
    const upload = { name: `${stem}.${info.extension}`, mime: info.mime, data };
    return { upload, ...(info.width === undefined ? {} : { width: info.width }), ...(info.height === undefined ? {} : { height: info.height }) };
}
